# Generated by Django 3.2.9 on 2021-12-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno',
            new_name='nome',
        ),
    ]
